### ISSUE TITLE
some ideas for more instances

### ISSUE THREAD

**Issue by hejjoe** [tante/hypebot-config#2]
1. ohai.social [via](https://ohai.social/@jascha/112033006109966065)
2. eupolicy.social [via](https://eupolicy.social/@ilumium/112033750138977287)
3. openbiblio.social [via](https://openbiblio.social/@Lambo/112033755759612380)
4. nfdi.social [via](https://openbiblio.social/@Lambo/112033755759612380)
5. fedihum.org [via](https://openbiblio.social/@Lambo/112033755759612380)
6. social.ftm.nl [via](https://social.ftm.nl/@EricChrSmit/112036178293014683)
7. 23.social
8. d-64.social
9. vis.social
10. todon.eu
11. kolektiva.social
12. social.bund.de
13. ard.social
14. social.bbc
15. aoir.social
16. social.coop
17. sciences.social
18. mastodon.design
19. typo.social
20. assemblag.es
21. mastodon.bits-und-baeume.org
22. bewegung.social
23. post.lurk.org 
24. bildung.social
25. dju.social
26. mastodon.xyz
27. mastodon.cc
28. social.prepedia.org
29. social.network.europa.eu
30. ioc.exchange
31. union.place

**Comment by tante** [comment]
Thanks!

I added a bunch to the bot. I left out some very small instances and some that are very local to Germany/Europe to not increase to whiteness and eurocentrism even more.
